export const SET_CURRENT_PERSON = "SET_CURRENT_PERSON";
export const GET_PERSON = "GET_PERSON";

export const GET_ERRORS = "GET_ERRORS";

export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

export const GET_TOTAL_MONTHLY_DISTANCE = "GET_TOTAL_MONTHLY_DISTANCE";
export const GET_TOTAL_MONTHLY_CALORIES = "GET_TOTAL_MONTHLY_CALORIES";
export const GET_TOTAL_MONTHLY_STEPS = "GET_TOTAL_MONTHLY_STEPS";
